name: Deploy to Raspberry Pi

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Deploy updates
        run: |
          cd /home/cosmoss/Documents/Sogalen
          git pull origin main
          npm install --omit=dev
          node deploy-commands.js
          pm2 startOrReload main.js --name "sogalen"
          pm2 save